Mobile skeleton;portfolio
jemutakiplagat/portfolio pull request #1
Opened 2022-04-25 15:28 UTC by jemutakiplagat

creating new files
Add images 
Adding CSS styles 
Add GitHub folders
Creating GitHub workflow
Creating new files to check linters

2022-04-25 15:57 UTC, roshan-bajgain requested changes
Hi @jemutakiplagat, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/LRBqvC9nH0pN776TcD/giphy.gif"/>

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight :tada: :champagne: 
- Nice PR description and title :+1: 
- Nice README file :heavy_check_mark:
- No linter error :heavy_check_mark:
- GitHub flow is followed :+1:


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-25 15:57 UTC, roshan-bajgain commented on index.html
> +        <div class="full-wrapper">
- [ ] The container of the section should be a header tag for better semantic HTML. Kindly fix it.

2022-04-25 15:57 UTC, roshan-bajgain commented on index.html
> +                  </div>
- [ ] The log on the left should have a link (`a` tag) because we use the `a` tag to create a hyperlink on the webpage. So kindly fix it

2022-04-26 09:50 UTC, phelian23 approved these changes
Hi @jemutakiplagat, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] I will suggest that when adding margins, width, and height to your projects, always favor percent-based units (%, vw, vh) over fixed units (px), as this will help improve the responsiveness of your page.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 09:57 UTC, merged