Desktop version
jemutakiplagat/portfolio pull request #5
Opened 2022-05-06 13:26 UTC by jemutakiplagat

-Added @media queries for responsiveness
-modified some css to fit wide screen

2022-05-06 14:52 UTC, CollinsTatang requested changes
Hi @jemutakiplagat, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 


- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 14:52 UTC, CollinsTatang commented on index.css
> +} */
- [ ] Please remove all commented code from your codebase to make it clean and easy to maintain.

2022-05-06 14:52 UTC, CollinsTatang commented on index.css
> +  } */
- [ ] Please remove all commented code from your codebase to make it clean and easy to maintain.

2022-05-06 14:52 UTC, CollinsTatang commented on index.css
> +  height: 72px; */
- [ ] Please remove all commented code from your codebase to make it clean and easy to maintain.

2022-05-06 14:52 UTC, CollinsTatang commented on index.html
> +
- [ ] Please work on your desktop design view following the Figma [Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)
### **Take a look at your design**
![head](https://user-images.githubusercontent.com/55596970/167155462-cc195588-ff10-4e43-8926-80250245afa6.png)
### **This is Figmal Design**
![destop](https://user-images.githubusercontent.com/55596970/167155617-82446b1d-c0fc-4a21-b154-6080709db94d.png)

2022-05-06 14:52 UTC, CollinsTatang commented on index.css
> +  display: grid;
- [ ] Please work on your mobile design to still look as expected. The project is no more responsive at any screen size
### **Take A Look at Your Mobile Design**
![mobile](https://user-images.githubusercontent.com/55596970/167156555-40571d97-88ec-43ca-b6a5-5b347222c867.png)

2022-05-06 14:52 UTC, CollinsTatang commented on index.css
>    display: flex;
- [ ] Please used the media query for the Desktop breakpoint in your CSS.
![res](https://user-images.githubusercontent.com/55596970/167157660-9db036c1-632e-4e8f-ab47-be4c950896db.png)

2022-05-07 18:59 UTC, jemutakiplagat commented
-Made the page responsive 
-Removed all comments to make my code clean

2022-05-07 19:13 UTC, arslanbisharat commented
Hi,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 19:15 UTC, merged